module.exports={
    clientRedis:require('./c_clientRedis'),
    clientAwsIot:require('./c_clientAwsIot'),
    hubWs:require('./c_hubWs'),
    clientWs:require('./c_clientWs'),
    http:require('./c_http'),
    protoWork:require('./protoWork'),
    jsInit:require('./jsInit')
};